#!/bin/bash

if [ ! -f "$HOME/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs" ]; then
  mkdir $HOME/travis-phantomjs
  wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $HOME/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  tar -xvf $HOME/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $HOME/travis-phantomjs
fi
export PATH=$HOME/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
